### ISSUE TITLE
Repo cleanup / gitignore

### ISSUE THREAD

**Issue by darianmiller** [BitmasterXor/Delphi_Basic_UDP_Holepunching#1]
Just saw you repo - congrats.  I suggest that you add a .gitignore customized for Delphi
Remove __history
.local
.identcache
.res
.stat

**Comment by BitmasterXor** [comment]
Thanks Darian, I don't really work directly with GitHub API or anything like that I just make the code and upload as one solution. 
I suppose I really should let the IDE upload / commit for me lol. Or use Git for desktop, don't want to fill up GitHub servers with too much crud that's not needed, also don't really fancy people seeing my "Failed past attempts in history LOL" 

I'll take the time to cleanup my other repo's as well. 

Thanks for the tip man Much! Much! appreciated.

**Comment by darianmiller** [comment]
When you create a repo on GitHub, one of the options is to pick a GitIgnore and there is one available for Delphi.  It helps keep your repos cleaner.

![image](https://github.com/user-attachments/assets/9d572528-7019-4c5b-9752-4385ccae71d7)

Cool repo though!

**Comment by BitmasterXor** [comment]
Darian sir! you are a LIFE SAVER! I had no clue didn't even bother too look around LOL! From now on you can bet I will be using that :) Thanks BIG TIME! ill close this issue as soon as my other repo's are cleared.

**Comment by BitmasterXor** [comment]
@darianmiller 

All Repos cleared out
history Folder 
.local
.identcache
.res
.stat
.dres (saw some of these as well) if I'm not mistaken they are just resource files which also get generated at build time... used to use them when saving settings and files inside of ".exe" Resources.

If you notice anything else that needs to be fixed PLEASE let me know! and thank you again Sir! Knowledge hath increased!

**Comment by darianmiller** [comment]
It's minor, but it makes your repositories more professional looking.

You should also remove the *.local 

Here's a reference.  Check out the last column "Keep in version control"
https://docwiki.embarcadero.com/RADStudio/Athens/en/File_Extensions_of_Files_Generated_by_RAD_Studio

**Comment by BitmasterXor** [comment]
@darianmiller Thank you man, this page in fact makes everything Extremely clear for me to understand. I'll also share this link on to my friends... there was an issue recently where they deleted some files in a project and they where core files (had to re-send them all to me so I could compile / Build) so I'm sure this page will assist them in understanding as well LOL. 

Thanks Again Darian!

**Comment by darianmiller** [comment]
You're welcome.   This all started with your work on a new repo.  Thank you!
